name: portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_KEYS }}" > id_rsa
          chmod 600 id_rsa

      - name: Connect SSH and execute commands
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i id_rsa ec2-user@ec2-13-55-149-226.ap-southeast-2.compute.amazonaws.com '
            ls &&
            echo "done connecting" &&
            sudo rm -rf /home/ec2-user/currentPortfolio/portfolio/ 
            echo "old removed" &&
            cd /home/ec2-user/currentPortfolio/ &&
            git clone https://github.com/optimisticlucifer/portfolio.git &&
            cd /home/ec2-user/currentPortfolio/portfolio/ &&
            ls &&
            git stash &&
            git fetch &&
            git checkout master &&
            git pull origin master &&
            echo "done travel" &&
            npm  install --silent &&
            npm run dev -- --port=3000 --host &&
            echo "done connect"'
