name: portfolio

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_KEYS }}" > id_rsa
          chmod 600 id_rsa

      - name: Connect SSH
        run: |
          ssh -tt -o StrictHostKeyChecking=no -i id_rsa ec2-3-27-217-251.ap-southeast-2.compute.amazonaws.com
          cd currentPortfolio/
          cd portfolio/
          npm run dev -- --port --host
          echo "done connect"
